#!/data/data/com.termux/files/usr/bin/sh

TPLUG_CLI_DIR="/data/data/com.termux/files/home/.termux-plugins-cli"
COMMAND_DIR="$TPLUG_CLI_DIR/commands/"

show_help() {
    echo "Usage: tplug <command> [options]"
    echo
    echo "Commands:"
    echo "  add <plugin_name>            Add a plugin from the local directory."
    echo "  install [--all | <name>]     Install plugins from the repository."
    echo "  logs [-c] <service_name>     View current logs for service. Use [-c] to clear logs"
    echo "  list-available               List all available plugins in the repository."
    echo "  list-services                List all termux services."
    echo "  list-plugins                 List all installed plugins."
    echo "  remove [--purge] <service_name> Remove a termux service. Use '--purge' to remove logs."
    echo "  remove-plugin <plugin_name>  Remove a plugin."
    echo "  --help                       Show this help message."
    echo
}

check_dependencies() {
    REQUIRED_COMMANDS="git pkg"
    for cmd in $REQUIRED_COMMANDS; do
        if ! command -v $cmd >/dev/null; then
            error "Required command '$cmd' is not installed."
            exit 1
        fi
    done
}

case "$1" in
    add) shift; source "$COMMAND_DIR/add.sh" ;;
    install) shift; source "$COMMAND_DIR/install.sh" ;;
    logs) shift; source "$COMMAND_DIR/logs.sh" ;;
    list-plugins) source "$COMMAND_DIR/list-plugins.sh" ;;
    list-services) source "$COMMAND_DIR/list-services.sh" ;;
    list-available) source "$COMMAND_DIR/list-available.sh" ;;
    remove) shift; source "$COMMAND_DIR/remove.sh" ;;
    remove-plugin) shift; source "$COMMAND_DIR/remove-plugin.sh" ;;
    --help) show_help ;;
    *) show_help ;;
esac
